builds:
  -  # First Build
    env:
      - CGO_ENABLED=0
    main: ./cmd/fleeting-plugin-openstack
    ldflags: >-
      -s -w
      -X github.com/codecentric/fleeting-plugin-openstack.Version={{.Version}}
      -X github.com/codecentric/fleeting-plugin-openstack.Revision={{.FullCommit}}
      -X github.com/codecentric/fleeting-plugin-openstack.Branch={{.Branch}}
      -X github.com/codecentric/fleeting-plugin-openstack.BuildUser=goreleaser@github-actions
      -X github.com/codecentric/fleeting-plugin-openstack.BuildDate={{time "20060102-15:04:05"}}

    # Set the binary output location to bin/ so archive will comply with Sensu Go Asset structure
    binary: bin/{{ .ProjectName }}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    targets:
      - linux_386
      - linux_amd64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
